import 'dart:io';
import 'dart:math';

import 'package:flutter/services.dart' show rootBundle;
import 'package:path_provider/path_provider.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:share_plus/share_plus.dart';

const lockedDisclaimer = 'This screening result is not a medical diagnosis. It is a triage aid for trained health workers only. All results require confirmation by a qualified medical professional. Do not make treatment decisions based on this result alone.';

class PdfService {
  Future<File> generate({required String anemiaRisk, required String jaundiceRisk, String? patientReference, required String appVersion, required DateTime capturedAt, bool dualHigh = false}) async {
    final regular = pw.Font.ttf(await rootBundle.load('assets/fonts/NotoSans-Regular.ttf'));
    final document = pw.Document(theme: pw.ThemeData.withFont(base: regular));
    final patient = patientReference == null || patientReference.trim().isEmpty ? '[Not provided]' : patientReference.trim();
    final children = <pw.Widget>[
      pw.Text('VYTRA', style: pw.TextStyle(fontSize: 22, fontWeight: pw.FontWeight.bold)),
      pw.SizedBox(height: 12),
      pw.Text('Patient: $patient'),
      pw.Text('Date and time: ${capturedAt.toIso8601String()}'),
      pw.SizedBox(height: 18),
      pw.Text('Anemia risk: $anemiaRisk'),
      pw.Text('Jaundice risk: $jaundiceRisk'),
      if (dualHigh) pw.Padding(padding: const pw.EdgeInsets.symmetric(vertical: 14), child: pw.Text('Immediate referral recommended. Accompany the patient to the PHC today.', style: pw.TextStyle(fontWeight: pw.FontWeight.bold))),
      pw.SizedBox(height: 20),
      pw.Text(lockedDisclaimer),
      pw.Spacer(),
      pw.Text('Generated by VYTRA v$appVersion. This is not a medical document. For use by trained ASHA workers only.', style: const pw.TextStyle(fontSize: 9)),
    ];
    document.addPage(pw.Page(build: (_) => pw.DefaultTextStyle(style: pw.TextStyle(font: regular, fontSize: 12), child: pw.Column(crossAxisAlignment: pw.CrossAxisAlignment.start, children: children))));
    final dir = await getTemporaryDirectory();
    final suffix = List.generate(4, (_) => 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'[Random.secure().nextInt(36)]).join();
    final file = File('${dir.path}/SCREEN_${_date(capturedAt)}_$suffix.pdf');
    await file.writeAsBytes(await document.save());
    return file;
  }

  Future<void> share(File file) => Share.shareXFiles([XFile(file.path)], text: 'VYTRA referral screening');

  String _date(DateTime value) => '${value.year.toString().padLeft(4, '0')}${value.month.toString().padLeft(2, '0')}${value.day.toString().padLeft(2, '0')}';
}
